TTree* tree = (TTree*)gFile->Get("hltbitanalysis/HltTree")

tree->GetEntries("HLT_HIGEDPhoton10_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton15_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton20_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton30_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton40_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton50_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton60_L1Seeded > 0")

tree->GetEntries("HLT_HIGEDPhoton10_HECut_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton15_HECut_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton20_HECut_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton30_HECut_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton40_HECut_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton50_HECut_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton60_HECut_L1Seeded > 0")

tree->GetEntries("HLT_HIGEDPhoton10_EB_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton15_EB_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton20_EB_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton30_EB_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton40_EB_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton50_EB_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton60_EB_L1Seeded > 0")

tree->GetEntries("HLT_HIGEDPhoton10_EB_HECut_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton15_EB_HECut_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton20_EB_HECut_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton30_EB_HECut_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton40_EB_HECut_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton50_EB_HECut_L1Seeded > 0")
tree->GetEntries("HLT_HIGEDPhoton60_EB_HECut_L1Seeded > 0")

tree->GetEntries("HLT_HIGEDPhoton10 > 0")
tree->GetEntries("HLT_HIGEDPhoton15 > 0")
tree->GetEntries("HLT_HIGEDPhoton20 > 0")
tree->GetEntries("HLT_HIGEDPhoton30 > 0")
tree->GetEntries("HLT_HIGEDPhoton40 > 0")
tree->GetEntries("HLT_HIGEDPhoton50 > 0")
tree->GetEntries("HLT_HIGEDPhoton60 > 0")

tree->GetEntries("HLT_HIGEDPhoton10_HECut > 0")
tree->GetEntries("HLT_HIGEDPhoton15_HECut > 0")
tree->GetEntries("HLT_HIGEDPhoton20_HECut > 0")
tree->GetEntries("HLT_HIGEDPhoton30_HECut > 0")
tree->GetEntries("HLT_HIGEDPhoton40_HECut > 0")
tree->GetEntries("HLT_HIGEDPhoton50_HECut > 0")
tree->GetEntries("HLT_HIGEDPhoton60_HECut > 0")

tree->GetEntries("HLT_HIGEDPhoton10_EB > 0")
tree->GetEntries("HLT_HIGEDPhoton15_EB > 0")
tree->GetEntries("HLT_HIGEDPhoton20_EB > 0")
tree->GetEntries("HLT_HIGEDPhoton30_EB > 0")
tree->GetEntries("HLT_HIGEDPhoton40_EB > 0")
tree->GetEntries("HLT_HIGEDPhoton50_EB > 0")
tree->GetEntries("HLT_HIGEDPhoton60_EB > 0")

tree->GetEntries("HLT_HIGEDPhoton10_EB_HECut > 0")
tree->GetEntries("HLT_HIGEDPhoton15_EB_HECut > 0")
tree->GetEntries("HLT_HIGEDPhoton20_EB_HECut > 0")
tree->GetEntries("HLT_HIGEDPhoton30_EB_HECut > 0")
tree->GetEntries("HLT_HIGEDPhoton40_EB_HECut > 0")
tree->GetEntries("HLT_HIGEDPhoton50_EB_HECut > 0")
tree->GetEntries("HLT_HIGEDPhoton60_EB_HECut > 0")

tree->GetEntries("HLT_HIIslandPhoton10_Eta3p1 > 0")
tree->GetEntries("HLT_HIIslandPhoton15_Eta3p1 > 0")
tree->GetEntries("HLT_HIIslandPhoton20_Eta3p1 > 0")
tree->GetEntries("HLT_HIIslandPhoton30_Eta3p1 > 0")
tree->GetEntries("HLT_HIIslandPhoton40_Eta3p1 > 0")
tree->GetEntries("HLT_HIIslandPhoton50_Eta3p1 > 0")
tree->GetEntries("HLT_HIIslandPhoton60_Eta3p1 > 0")

tree->GetEntries("HLT_HIIslandPhoton10_Eta1p5 > 0")
tree->GetEntries("HLT_HIIslandPhoton15_Eta1p5 > 0")
tree->GetEntries("HLT_HIIslandPhoton20_Eta1p5 > 0")
tree->GetEntries("HLT_HIIslandPhoton30_Eta1p5 > 0")
tree->GetEntries("HLT_HIIslandPhoton40_Eta1p5 > 0")
tree->GetEntries("HLT_HIIslandPhoton50_Eta1p5 > 0")
tree->GetEntries("HLT_HIIslandPhoton60_Eta1p5 > 0")

