TTree* tree = (TTree*)gFile->Get("hltbitanalysis/HltTree")

tree->GetEntries("HLT_GEDPhoton10 > 0")
tree->GetEntries("HLT_GEDPhoton15 > 0")
tree->GetEntries("HLT_GEDPhoton20 > 0")
tree->GetEntries("HLT_GEDPhoton30 > 0")
tree->GetEntries("HLT_GEDPhoton40 > 0")
tree->GetEntries("HLT_GEDPhoton50 > 0")
tree->GetEntries("HLT_GEDPhoton60 > 0")

tree->GetEntries("HLT_GEDPhoton10_HECut > 0")
tree->GetEntries("HLT_GEDPhoton15_HECut > 0")
tree->GetEntries("HLT_GEDPhoton20_HECut > 0")
tree->GetEntries("HLT_GEDPhoton30_HECut > 0")
tree->GetEntries("HLT_GEDPhoton40_HECut > 0")
tree->GetEntries("HLT_GEDPhoton50_HECut > 0")
tree->GetEntries("HLT_GEDPhoton60_HECut > 0")

tree->GetEntries("HLT_GEDPhoton10_EB > 0")
tree->GetEntries("HLT_GEDPhoton15_EB > 0")
tree->GetEntries("HLT_GEDPhoton20_EB > 0")
tree->GetEntries("HLT_GEDPhoton30_EB > 0")
tree->GetEntries("HLT_GEDPhoton40_EB > 0")
tree->GetEntries("HLT_GEDPhoton50_EB > 0")
tree->GetEntries("HLT_GEDPhoton60_EB > 0")

tree->GetEntries("HLT_EG10UM > 0")
tree->GetEntries("HLT_EG15UM > 0")
tree->GetEntries("HLT_EG20UM > 0")
tree->GetEntries("HLT_EG30UM > 0")
tree->GetEntries("HLT_EG40UM > 0")
tree->GetEntries("HLT_EG50UM > 0")
tree->GetEntries("HLT_EG60UM > 0")

tree->GetEntries("HLT_EG10HEUM > 0")
tree->GetEntries("HLT_EG15HEUM > 0")
tree->GetEntries("HLT_EG20HEUM > 0")
tree->GetEntries("HLT_EG30HEUM > 0")
tree->GetEntries("HLT_EG40HEUM > 0")
tree->GetEntries("HLT_EG50HEUM > 0")
tree->GetEntries("HLT_EG60HEUM > 0")

tree->GetEntries("HLT_EG10EBUM > 0")
tree->GetEntries("HLT_EG15EBUM > 0")
tree->GetEntries("HLT_EG20EBUM > 0")
tree->GetEntries("HLT_EG30EBUM > 0")
tree->GetEntries("HLT_EG40EBUM > 0")
tree->GetEntries("HLT_EG50EBUM > 0")
tree->GetEntries("HLT_EG60EBUM > 0")

tree->GetEntries("HLT_HISinglePhoton10_Eta3p1 > 0")
tree->GetEntries("HLT_HISinglePhoton15_Eta3p1 > 0")
tree->GetEntries("HLT_HISinglePhoton20_Eta3p1 > 0")
tree->GetEntries("HLT_HISinglePhoton30_Eta3p1 > 0")
tree->GetEntries("HLT_HISinglePhoton40_Eta3p1 > 0")
tree->GetEntries("HLT_HISinglePhoton50_Eta3p1 > 0")
tree->GetEntries("HLT_HISinglePhoton60_Eta3p1 > 0")

tree->GetEntries("HLT_HISinglePhoton10_Eta1p5 > 0")
tree->GetEntries("HLT_HISinglePhoton15_Eta1p5 > 0")
tree->GetEntries("HLT_HISinglePhoton20_Eta1p5 > 0")
tree->GetEntries("HLT_HISinglePhoton30_Eta1p5 > 0")
tree->GetEntries("HLT_HISinglePhoton40_Eta1p5 > 0")
tree->GetEntries("HLT_HISinglePhoton50_Eta1p5 > 0")
tree->GetEntries("HLT_HISinglePhoton60_Eta1p5 > 0")

