TTree* tree = (TTree*)gFile->Get("hltbitanalysis/HltTree")

tree->GetEntries("HLT_GEDPhoton10 > 0")
tree->GetEntries("HLT_GEDPhoton15 > 0")
tree->GetEntries("HLT_GEDPhoton20 > 0")
tree->GetEntries("HLT_GEDPhoton30 > 0")
tree->GetEntries("HLT_GEDPhoton40 > 0")
tree->GetEntries("HLT_GEDPhoton50 > 0")
tree->GetEntries("HLT_GEDPhoton60 > 0")

tree->GetEntries("HLT_GEDPhoton10_HECut > 0")
tree->GetEntries("HLT_GEDPhoton15_HECut > 0")
tree->GetEntries("HLT_GEDPhoton20_HECut > 0")
tree->GetEntries("HLT_GEDPhoton30_HECut > 0")
tree->GetEntries("HLT_GEDPhoton40_HECut > 0")
tree->GetEntries("HLT_GEDPhoton50_HECut > 0")
tree->GetEntries("HLT_GEDPhoton60_HECut > 0")

tree->GetEntries("HLT_GEDPhoton10_EB > 0")
tree->GetEntries("HLT_GEDPhoton15_EB > 0")
tree->GetEntries("HLT_GEDPhoton20_EB > 0")
tree->GetEntries("HLT_GEDPhoton30_EB > 0")
tree->GetEntries("HLT_GEDPhoton40_EB > 0")
tree->GetEntries("HLT_GEDPhoton50_EB > 0")
tree->GetEntries("HLT_GEDPhoton60_EB > 0")

tree->GetEntries("HLT_HISinglePhoton10_Eta3p1 > 0")
tree->GetEntries("HLT_HISinglePhoton15_Eta3p1 > 0")
tree->GetEntries("HLT_HISinglePhoton20_Eta3p1 > 0")
tree->GetEntries("HLT_HISinglePhoton30_Eta3p1 > 0")
tree->GetEntries("HLT_HISinglePhoton40_Eta3p1 > 0")
tree->GetEntries("HLT_HISinglePhoton50_Eta3p1 > 0")
tree->GetEntries("HLT_HISinglePhoton60_Eta3p1 > 0")

tree->GetEntries("HLT_HISinglePhoton10_Eta1p5 > 0")
tree->GetEntries("HLT_HISinglePhoton15_Eta1p5 > 0")
tree->GetEntries("HLT_HISinglePhoton20_Eta1p5 > 0")
tree->GetEntries("HLT_HISinglePhoton30_Eta1p5 > 0")
tree->GetEntries("HLT_HISinglePhoton40_Eta1p5 > 0")
tree->GetEntries("HLT_HISinglePhoton50_Eta1p5 > 0")
tree->GetEntries("HLT_HISinglePhoton60_Eta1p5 > 0")

